### ISSUE TITLE
Is there no problem with this library?

### ISSUE THREAD

**Issue by shengyonghappy** [audionamix/rtff#5]
When I input a flat signal with a amplitude of 0.5 the output result is wrong。

**Comment by maxmarsc** [comment]
Hi @shengyonghappy , unfortunately no one is actually in charge of this library anymore as the R&D team at Audionamix is kinda dead. So even if there's an issue identified, this repository couldn't really be updated for the fix :/

But as far as I recall this issue doesn't ring a bell, did you checked this is not a latency issue ? RTFF does introduce some latency to the input signal.

**Comment by shengyonghappy** [comment]
@maxmarsc  Thank you for your reply, It's not just the latency. I also tried to input the sinusoidal signal, but the output is not what I think it is.

**Comment by maxmarsc** [comment]
Sorry for the long delay ^^" do you have more precision on what's wrong on your output please ?
