### ISSUE TITLE
obsolete cmake directory

### ISSUE THREAD

**Issue by kweiwen** [audionamix/rtff#6]
To Whom It May Concern,

I hope this message finds you well. I am writing to bring to your attention an issue related to the `add_mkl.cmake` file.

It has come to my attention that the latest Windows oneAPI MKL module is not installed in the expected directory of `Program Files (x86)/IntelSWTools/compilers_and_libraries/windows`, but rather in `Program Files (x86)/Intel/oneAPI/mkl/latest-version`. As a result, the current version of `add_mkl.cmake` may not function as intended.

Therefore, would you revise the `add_mkl.cmake` file to reflect this change in directory and ensure that other dependencies can be built easily.

Thank you.

**Comment by SuperKogito** [comment]
In my case the new MKL path looks like this `C:\Program Files (x86)\Intel\oneAPI\mkl\latest`. However, changing the path in the cmake won't solve this issue, since it seems that the files names are also different.

**Comment by kweiwen** [comment]
@SuperKogito Hi Malek, are you trying to use `audionamix` in `spleeterpp`?

**Comment by SuperKogito** [comment]
yes, I am trying to build a VST similar to https://github.com/gvne/vstSpleeter.

**Comment by maxmarsc** [comment]
Hi there, I'm the only "maintainer" left on this project (the R&D departement of Audionamix has been closed). Unfortunately the whole CI/testing pipeline configuration is broken and it would require a bit of work to get all this back in a good shape. And I don't really have time for this right now.

It's indeed no surprise for me that the configuration is outdated, especially for Windows. I don't have a Windows setup right now, but if you provide a quick fix I'd be glad to merge it, although I wouldn't be able to check the validity of it from the automated pipelines

**Comment by kweiwen** [comment]
Hi Max,

Thanks for the reply, the issue I am facing is not only cmake directory but also as a dependency for `vstSpleeter`. Currently I am trying to decouple the root cause. However, I don't have the means to verify the functionality of `rfft` solely by implementing `vstSpleeter`. Do you have a better suggestion?

**Comment by maxmarsc** [comment]
You mean you have troubles with mkl's cmake integration with both `rtff` and `vstSpleeter` at the same time ?

**Comment by kweiwen** [comment]
Yes, I have successfully compiled VST on both Mac OSX (M1) and Win10 (AMD R5), but I am experiencing a glitch sound every 10-12 seconds from the VST output. Even if I bypassed the mkl option in CMakeList, the glitch still persists.

**Comment by maxmarsc** [comment]
I doubt such a glitch would come from bad cmake configuration, usually an obsolete cmake configuration would mostly prevent you from compiling/linking.

**Comment by kweiwen** [comment]
Yes, I think the glitch is irrelevant to the cmake configuration, but back to your previous question: @SuperKogito mentioned his mkl directory is located at `C:\Program Files (x86)\Intel\oneAPI\mkl\latest`. But mine mkl directory is located at `Program Files (x86)\Intel\oneAPI\mkllatest-version`. I don't think a merge will be a good idea, therefore I think you can simply close this issue, thanks for your help!

**Comment by maxmarsc** [comment]
Ok

**Comment by SuperKogito** [comment]
@kweiwen I have the exact same glitch in the output sound. Feel free to shoot me an email to discuss the issue. @maxmarsc Thank you for your support.

**Comment by kweiwen** [comment]
@SuperKogito mail sent! please check your gmail inbox, thanks
